version: '3.6'

services:
  mongo:
    image: mongo
    # restart: always
    ports:
      - 27017:27017
    # volumes:
    #   - db-data:/var/lib/mongo
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: admin
    #   MONGODB_USERNAME: root
    #   MONGODB_PASSWORD: admin
# volumes:
# db-data:
# sudo docker-compose -f mongodb.yml up -d
# sudo docker-compose -f mongodb.yml down
