version: '3.3'

services:
  postgresql-db:
    image: postgres:14.1
    container_name: psql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    networks:
      - turreta_network
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./sql_scripts:/docker-entrypoint-initdb.d # for creating a sql file to create schema or tables

networks:
  turreta_network:
    driver: bridge

volumes:
  db-data:
    driver: local
# sudo docker exec -it 3e86bb8cabd4 bash
# psql -U admin -d postgres
