global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  # Add your own targets here, e.g.:
  # - job_name: 'myapp'
  #   static_configs:
  #     - targets: ['host.docker.internal:8080']
